jan <- read.csv("NJAN_T_ONTIME_MARKETING.csv")
feb <- read.csv("NFEB_T_ONTIME_MARKETING.csv")
march <- read.csv("NMARCHT_ONTIME_MARKETING.csv")
april <- read.csv("APRIL_T_ONTIME_MARKETING.csv")
may <- read.csv("MAY_T_ONTIME_MARKETING.csv")
june <- read.csv("JUNE_T_ONTIME_MARKETING.csv")
july <- read.csv("JULY_T_ONTIME_MARKETING.csv")
aug <- read.csv("AUG_T_ONTIME_MARKETING.csv")
sept <- read.csv("SEPT_T_ONTIME_MARKETING.csv")
oct <- read.csv("OCT_T_ONTIME_MARKETING.csv")
nov <- read.csv("NOV_T_ONTIME_MARKETING.csv")
dec <- read.csv("DEC_T_ONTIME_MARKETING.csv")
new <- rbind(jan, feb)
new <- rbind( new, march)
new <- rbind( new, april)
new <- rbind( new, may)
new <- rbind( new, june)
new <- rbind( new, july)
new <- rbind( new, aug)
new <- rbind( new, sept)
new <- rbind( new, oct)
new <- rbind( new, nov)

final_flights <- rbind(new, dec)

saveRDS(final_flights, file = "final_flights.rds")

